# Generated by Django 4.2 on 2023-05-10 08:42

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile_bio_profile_created_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
