# Generated by Django 4.2 on 2023-05-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_remove_profile_picture_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Picture',
            new_name='picture',
        ),
    ]
