# Generated by Django 4.2 on 2023-05-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_picture_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='picture',
        ),
    ]
